name: Deploy to GitHub Pages

# This workflow will run on any push to the main branch or when manually triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permissions for the GitHub token to deploy to Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensures that only one deployment occurs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the static files (e.g., HTML, CSS, JS) to GitHub Pages
      - name: Upload static files to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # This uploads all the files in the root of your repository

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
